services:
  - type: web
    name: todo-app-backend
    env: node
    buildCommand: "npm install"
    startCommand: "node src/server.js"
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
    autoDeploy: true
    rootDir: backend
  - type: web
    name: todo-app-frontend
    env: node
    buildCommand: "npm install && npm run build"
    startCommand: "npx serve -s build"
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
    autoDeploy: true
    rootDir: frontend 