services:
  - type: web
    name: todo-app-backend
    env: node
    buildCommand: "npm install"
    startCommand: "node src/server.js"
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
    autoDeploy: true 