name: Deploy To-Do List Backend & Frontend to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest
    outputs:
      backend_url: ${{ steps.get-backend-url.outputs.backend_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Create .env file for backend
        run: echo "${{ secrets.BACKEND_ENV }}" > backend/.env

      - name: Build and push backend Docker image
        run: |
          gcloud builds submit ./backend --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/todo-backend

      - name: Deploy backend to Cloud Run
        run: |
          gcloud run deploy todo-backend \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/todo-backend \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --port 5000

      - name: Get backend Cloud Run URL
        id: get-backend-url
        run: |
          URL=$(gcloud run services describe todo-backend --platform managed --region us-central1 --format 'value(status.url)')
          echo "Backend URL: $URL"
          echo "backend_url=$URL" >> $GITHUB_OUTPUT

  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-and-deploy-backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Create .env file for frontend (con URL del backend)
        run: |
          echo "REACT_APP_API_URL=${{ needs.build-and-deploy-backend.outputs.backend_url }}" > frontend/.env
          if [ -n "${{ secrets.FRONTEND_ENV }}" ]; then
            echo "${{ secrets.FRONTEND_ENV }}" >> frontend/.env
          fi

      - name: Build and push frontend Docker image
        run: |
          gcloud builds submit ./frontend --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/todo-frontend

      - name: Deploy frontend to Cloud Run
        run: |
          gcloud run deploy todo-frontend \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/todo-frontend \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --port 3000